library(readr)
library(rpart)
library(rpart.plot)
library(e1071)
library(rattle)
library(lattice)
library(ggplot2)
library(RColorBrewer)
library(caret)
library(ROCR)
library(pROC)
library(rtweet)
library(stringr)
library(twitteR)
library(purrr)
library(tidytext)
library(tidyverse)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(broom)
library(ggplot2)
library(httr)
library(twitteR)
library(ROAuth)
library(readr)
library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
#install.packages("stringi")
library(stringi)
getwd()
setwd("/Users/madhavlavania/Desktop/FinalProject/")
#students_data <- data.frame(read.csv("StudentsCCC.csv", header=T, na.strings=c("","NA")))
students_data <- data.frame(read.csv("Student_TMA.csv", header=T, na.strings=c("","NA")))

#View(students_data)
str(students_data)
students_data <- students_data[,-c(1,2,5,14,16,18,21)] #removing theunwanted columns
na_count <-sapply(students_data, function(y) sum(length(which(is.na(y))))) #finding the total number of NAs in each column
na_count <- data.frame(na_count)
na_count #gives the number of NAs
students_data <- na.omit(students_data) #removing NAs where the student qualification was not known
na_count <-sapply(students_data, function(y) sum(length(which(is.na(y))))) #finding the total number of NAs in each column
na_count <- data.frame(na_count)
na_count #gives the number of NAs
students_data$imd_band <- gsub("%", "", students_data$imd_band)
View(students_data)
students_data <- students_data[,c(1:8,10:16,9)]
summary(students_data)
table(students_data$gender)
table(students_data$disability)
str(students_data)
students_data$gender<- factor(students_data$gender, levels = c ("M", "F"), labels = c(0, 1))
str(students_data$gender)
students_data$disability<- factor(students_data$disability, levels = c ("N", "Y"), labels = c(0, 1))
str(students_data$disability)
students_data$final_result<- factor(students_data$final_result, levels = c ("Pass", "Fail", "Distinction","Withdrawn"), labels = c(1, 0, 1, 2))
str(students_data$final_result)
table(students_data$final_result)
students_data$age_band<- factor(students_data$age_band, levels = c ("0-35", "35-55", "55<="), labels = c(0, 1, 2))
table(students_data$age_band)
str(students_data$age_band)
students_data$imd_band<- as.factor(students_data$imd_band)
str(students_data$imd_band)
table(students_data$imd_band)
students_data$imd_band<- factor(students_data$imd_band, levels = c ("0-10", "10-20", "20-30", "30-40", "40-50",
                                                                    "50-60", "60-70", "70-80","80-90", "90-100"), labels = c(0, 0, 0, 1, 1, 1, 1, 2, 2, 2))
students_data <- students_data[,-13]
students_data$highest_education<- factor(students_data$highest_education, levels = c ("A Level or Equivalent", "Lower Than A Level", "HE Qualification", "Post Graduate Qualification", "No Formal quals"), labels = c(0, 1, 2, 3, 4))
str(students_data$highest_education)
#write.csv(students_data, file= "/Users/madhavlavania/Desktop/FinalProject/cleanedData.csv", col.names = TRUE)
write.csv(students_data, file= "/Users/madhavlavania/Desktop/FinalProject/cleanedData1.csv", col.names = TRUE, row.names = FALSE)

