library(readr)
library(rpart)
library(rpart.plot)
library(e1071)
library(rattle)
library(lattice)
library(ggplot2)
library(RColorBrewer)
library(caret)
library(ROCR)
library(pROC)
library(rtweet)
library(stringr)
library(twitteR)
library(purrr)
library(tidytext)
library(tidyverse)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(broom)
library(ggplot2)
library(httr)
library(twitteR)
library(ROAuth)
library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
#install.packages("stringi")
library(stringi)
getwd()
setwd("/Users/madhavlavania/Desktop/FinalProject/")
students_data <- data.frame(read.csv("StudentsCCC.csv", header=T, na.strings=c("","NA")))
#View(students_data)
na_count <-sapply(students_data, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)
na_count

students_data <- students_data[,-c(14,18,21)]



